### PR TITLE
Feature/last updates

### PR DESCRIPTION
**Pull request by SoleCincis**
Refactor of DetailScreen and NewsItem & Implement an ImageCarousel

please have a look on the commits for detailed information ! 

peace

### CODE REVIEW

**Comment by pwilimzig** [comment]
There is always another "last update" :)

**Comment by donni106** [comment]
I rebased on latest master after merging #38 and will add the changes for categories in here.

**Comment by donni106** [comment]
Done 🚀 💯 

Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-08-02 at 15 09 31

**Comment by donni106** [comment]
Also fixed images and iframe sizes in HTML renderer 🚀 💯 

Simulator Screen Shot - iPhone 5s - 2019-08-02 at 15 47 41
Simulator Screen Shot - iPhone 5s - 2019-08-02 at 15 47 46

**Comment by donni106** [comment]
@SoleCincis have fun with reviewing the further changes. at least, I would say there are not that much.

**Pull request merged**
