### PR TITLE
Add eslint/import plugin

### LINKED ISSUE #126: [TypeScript] should we use recommended configs?
currently without recommended ruleset:

https://github.com/ikuseiGmbH/smart-village-app-app/blob/94bd1238af679bc33b72c53861317369ad81796d/.eslintrc.yml#L6-L8

should we add them?
https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#recommended-configs

```
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
```

### LINKED ISSUE #128: [ESlint] can the import structure be a rule?
there is a conversation about import rules in https://github.com/ikuseiGmbH/smart-village-app-app/pull/124#discussion_r530226155. maybe we can create a rule for that so that can be linted automatically?

### PR DESCRIPTION
**Pull request by digorath**
This PR is a suggestion and feedback on rule configuration is welcome.

## Changes proposed in this PR:

Added `imports` plugin for eslint to take care of import sorting and grouping.
* All rules are off by default, so the only added rule that is used from this plugin is `import/order`.

The only manually changed files in this PR are:
* package.json (through yarn add ...)
* eslintrc.yml
* queries/index.js (comments between imports)

---

Fixes #128

### CODE REVIEW

**Comment by donni106** [comment]
I will check it more deeply and plan to merge it for a 1.5.0 release in january.

**Comment by digorath** [comment]
I will update the PR towards the end of the year then.

**Comment by digorath** [comment]
updated with master after merging the typescript recommended and prettier part separately.

**Comment by donni106** [comment]
I made research and contacted the CodeClimate support.

**Comment by donni106** [comment]
No answer from CodeClimate, even after consultation in the meantime. They stay quite on this :(

**Comment by donni106** [comment]
i made deeper research and found a solution: https://github.com/codeclimate/codeclimate-eslint/issues/498#issuecomment-860870234

codeclimate successfully passes the analysis now: https://codeclimate.com/github/ikuseiGmbH/smart-village-app-app/builds/944

results: https://codeclimate.com/github/ikuseiGmbH/smart-village-app-app/compare/chore/add-typescript-eslint-recommended-and-prettier

**Review by donni106 — APPROVED** [review]

**Comment by digorath** [comment]
Replaced by #244 after cherry picking setup commits.

**Pull request closed without merging**
