### PR TITLE
Rename prop link in text style component

### LINKED ISSUE #50: Rename link prop on text component
In text style component, 'link' prop of regular text  needs to be renamed primary : this prop dyes regular text  in primary colour across the app .

### PR DESCRIPTION
**Pull request by SoleCincis**
- it's named primary now from primary color which is the characteristic of this prop

Resolves #50

### CODE REVIEW

**Comment by SoleCincis** [comment]
this 42 issues to fix are because I'm not using eslint ? I'm not sure what to do , should I reinstall it and push my code again ?

**Comment by donni106** [comment]
> this 42 issues to fix are because I'm not using eslint ? I'm not sure what to do , should I reinstall it and push my code again ?

it is the one file, where everything is indented 2 spaces to the right. you can see that in the differences of that file.
you could manually indent that back and push.
you do not need to install anything for doing that.

**Comment by donni106** [comment]
> TO TEST I couldn't test it because of missing accessibilityValue

what does that mean?
is you whole app not working anymore? your code changes has nothing to do with anything like the error is mentioning.
you local version of the app must work properly in order to merge. otherwise we cannot be sure, that this changes are fine to release.

**Comment by SoleCincis** [comment]
Not getting this error anymore , without doing any changes on the code . No comment .

**Comment by SoleCincis** [comment]
My local version runs without errors, but I'm still not seeing the content , but if I understood correctly this happens is master branch ? 
IMG_9804

**Comment by donni106** [comment]
> 
> 
> My local version runs without errors, but I'm still not seeing the content , but if I understood correctly this happens is master branch or branch based on master in this case ?
> IMG_9804

in master you are using the secrets object for "smart-village-app". when you copy the credentials from "bad-belzig-app", it behaves completly like the bad belzig branch. the master branch is not branded for a community but the data can be the same.
let's check this warning tomorrow in a call.

**Comment by SoleCincis** [comment]
When you have time we can take care of this and close it .

**Comment by donni106** [comment]
> 
> 
> When you have time we can take care of this and close it .

you can fix/lint the spaces/indentation until then please.

**Comment by SoleCincis** [comment]
it should be fixed

**Comment by SoleCincis** [comment]
this is tested and ready to be merged

**Pull request merged**
