### PR TITLE
feat(navigation options): stack web has OptionsWithShare now

### PR DESCRIPTION
**Pull request by SoleCincis**
- had some difficulties to understand new data flow for share logics , which are no more sitting inside the screen file 
- could not find another place to implement the share logics from navigation options 
- webView still has no visible share icon 

https://github.com/ikuseiGmbH/smart-village-app-app/issues/81

### CODE REVIEW

**Comment by SoleCincis** [comment]
@digorath short chat about this topic , when you have a bit of time ?

**Comment by donni106** [comment]
with the new setup, it is working for the detail screen. does this information maybe help?

**Comment by digorath** [comment]
Does @donni106 's hint help?

**Comment by SoleCincis** [comment]
@donni106 , @digorath yes Detail screen and its children are the first files the I scoured meticulously. 
That's why my commit 52e9944560bcbfacbd6a6c0276ea4f8b5503444e ,I also tried to use `options = {detailScreenOptions (headerRight)}`. Based on my understanding, the share logic resides entirely in screenOptions which is passed to AppstackNavigator, but I guess I'm missing something crucial ? 
Pls let's have a few words about this topic in tomorrow's call

**Comment by donni106** [comment]
@SoleCincis please have a later look somewhen again after finishing #234 and come back to us with questions.

**Comment by donni106** [comment]
What was going on here? Why is it closed?

**Comment by SoleCincis** [comment]
this branch was base on old master. 
So I did git rebase on master
Screenshot 2021-07-23 at 13 31 43
and then realising that I brought all the commits with me , I did a git reset --hard on master
Screenshot 2021-07-23 at 13 30 42

But when I force pushed , github didn't like what I did I guess and closed the branch ..

**Comment by donni106** [comment]
> But when I force pushed , github didn't like what I did I guess and closed the branch ..

you set on master and pushed, so github sees that the branch is equal to master and that a pull request from same to same is not necessary.

will you add work on the branch and reopen this PR?

**Comment by SoleCincis** [comment]
Yes I'm trying to add some work on this branch , I'm on it.

**Comment by SoleCincis** [comment]
@donni106 I created a new https://github.com/ikuseiGmbH/smart-village-app-app/pull/284

**Pull request closed without merging**
