### PR TITLE
chore: upgrade Expo SDK to 40

### PR DESCRIPTION
**Pull request by SoleCincis**
- followed instructions here:
  - https://blog.expo.io/expo-sdk-40-is-now-available-d4d73e67da33

SVA-124

**NOT DONE** updated on android emulator

### CODE REVIEW

**Comment by SoleCincis** [comment]
react-native-webview is still old "^10.7.0", didn't update to "11.0.0" because of error that couldn't be fixed ( from me ) 
following error + warning that would come up with last version RN webview: 
Screenshot 2020-12-11 at 13 30 37Screenshot 2020-12-11 at 15 06 52

https://github.com/expo/fyi/blob/master/no-registered-application.md my red screen is listed here , but no way to solve it .

**Comment by SoleCincis** [comment]
- this sdk version has updates on @expo/vector-icons , there for icons on tabBar needs to be tested 
- updated on android emulator needs to be done

**Comment by SoleCincis** [comment]
All our icons seems to be doing good , no change needed !

**Comment by digorath** [comment]
> react-native-webview is still old "^10.7.0", didn't update to "11.0.0" because of error that couldn't be fixed
> following error + warning that comes up with last version RN webview:
> Screenshot 2020-12-11 at 13 30 37Screenshot 2020-12-11 at 15 06 52
> 
> https://github.com/expo/fyi/blob/master/no-registered-application.md my red screen is listed here , but no way to solve it .

this has to do with the newly introduced map feature.
we use a fork of webviewleaflet that uses that specific version, because it used an even older one previously. I will provide a new commit hash to include in our package json

**Comment by donni106** [comment]
> > react-native-webview is still old "^10.7.0", didn't update to "11.0.0" because of error that couldn't be fixed
> > following error + warning that comes up with last version RN webview:
> ...
> 
> this has to do with the newly introduced map feature.
> we use a fork of webviewleaflet that uses that specific version, because it used an even older one previously. I will provide a new commit hash to include in our package json
> 
> edit: try this commit hash `d358a18c99cc0d9d9ea57de224b3917c4ad2a58f`
> (see changes here: [digorath/react-native-webview-leaflet@d358a18](https://github.com/digorath/react-native-webview-leaflet/commit/d358a18c99cc0d9d9ea57de224b3917c4ad2a58f))

@SoleCincis there is no react-native-webview update mentioned in the SDK 40 update. last one is the 10.7.0 in SDK 39.
how come that you wanted to update to 11?

**Comment by donni106** [comment]
> > > react-native-webview is still old "^10.7.0", didn't update to "11.0.0" because of error that couldn't be fixed
> > > following error + warning that comes up with last version RN webview:
> > > ...
> > 
> > 
> > this has to do with the newly introduced map feature.
> > we use a fork of webviewleaflet that uses that specific version, because it used an even older one previously. I will provide a new commit hash to include in our package json
> > edit: try this commit hash `d358a18c99cc0d9d9ea57de224b3917c4ad2a58f`
> > (see changes here: [digorath/react-native-webview-leaflet@d358a18](https://github.com/digorath/react-native-webview-leaflet/commit/d358a18c99cc0d9d9ea57de224b3917c4ad2a58f))
> 
> @SoleCincis there is no react-native-webview update mentioned in the [SDK 40 changelog](https://github.com/expo/expo/blob/master/CHANGELOG.md). last one is the 10.7.0 in SDK 39.
> how come that you wanted to update to 11?
> 
> @digorath thanks for the new commit hash. we can use that, when Expo releases a version with react-native-webview 11

when running `expo upgrade` it will be updated. so they forgot (?) to mention it in their changelog maybe.

Bildschirmfoto 2020-12-15 um 16 43 44

i will use the new commit hash from the fork.

**Review by donni106 — APPROVED** [review]
thanks, made adjustments.
will be included for the 1.5.0 update in january

**Pull request merged**
